version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: evidyalaya_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eschool2026_secret
      POSTGRES_DB: evidyalaya
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
